AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template to create S3 Bucket, VPC, and IAM Role for Dev environment"

Resources:
  # S3 Bucket para entorno Dev
  DevS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "company-dev-environment-bucket"
      AccessControl: "Private"
      Tags:
        - Key: "Environment"
          Value: "Development"
        - Key: "Department"
          Value: "Engineering"

  # VPC para entorno Dev
  DevVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "10.1.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: "Name"
          Value: "Company-Dev-VPC"
        - Key: "Environment"
          Value: "Development"
        - Key: "Department"
          Value: "Engineering"

  # IAM Role para el entorno Dev
  DevIAMRole:
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: "DevEnvironmentRole"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "DevS3AccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:ListBucket"
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource: 
                  - !Sub "arn:aws:s3:::company-dev-environment-bucket/*"
        - PolicyName: "DevVPCAccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ec2:Describe*"
                Resource: "*"
      Tags:
        - Key: "Environment"
          Value: "Development"
        - Key: "Department"
          Value: "Engineering"

Outputs:
  S3BucketName:
    Description: "Name of the S3 bucket for the Dev environment"
    Value: !Ref DevS3Bucket

  VPCID:
    Description: "ID of the VPC for the Dev environment"
    Value: !Ref DevVPC

  IAMRoleName:
    Description: "Name of the IAM Role for the Dev environment"
    Value: !Ref DevIAMRole
